//
//  GalaxyWild.h
//  TauGame
//
//  Created by Ian Terrell on 8/9/11.
//  Copyright (c) 2011 Ian Terrell. All rights reserved.
//

/**
 * Debug settings
 */

//#define DEBUG_LEVEL  [ClassicHorde class]
//#define DEBUG_BIGGUN [BigSpinner class]


/**
 * Multiplier
 */

#define MULTIPLIER_PER_HIT  1
#define MULTIPLIER_PER_KILL 3
#define MAX_MULTIPLIER      999
#define MIN_MULTIPLIER      10

#define MULTIPLIER_DECAY_INTERVAL 3
#define MULTIPLIER_DECAY_AMOUNT   1

/**
 * Powerups
 */

#define SCORE_BONUS_CHANCE 0.75
#define SCORE_BONUS_AMOUNT 100

/**
 * Levels
 */
#define NUM_GAME_LEVELS 4

/**
 * Fighter Config
 */

#define FIGHTER_INITIAL_LIVES  3
#define FIGHTER_INITIAL_HEALTH 3
#define FIGHTER_MAX_HEALTH     3

#define FIGHTER_INITIAL_SHOT_SPEED 1.0

#define FIGHTER_BULLET_X_SPREAD_FACTOR 3.2
#define FIGHTER_BULLET_Y_SPREAD_FACTOR 3.0
#define FIGHTER_BULLET_Y_VELOCITY 6.0
#define FIGHTER_BULLET_X_VELOCITY_FACTOR 0.75

#define FIGHTER_INITIAL_NUM_BULLETS 1
#define FIGHTER_INITIAL_NUM_SHOTS 10
#define FIGHTER_MAX_BULLETS 3
#define FIGHTER_MAX_SHOTS 10

#define FIGHTER_MAX_VELOCITY 10
#define FIGHTER_ACCELEROMETER_SENSITIVITY 35
#define FIGHTER_TURN_FACTOR 5
#define FIGHTER_MAX_TURN (1.0/6)

/**
 * Classic Horde Mode
 */

#define HORDE_LEVELS_PER_HITPOINT 20

#define HORDE_MAX_ROWS 6
#define HORDE_INITIAL_ROWS 1
#define HORDE_LEVELS_PER_ROW NUM_GAME_LEVELS

#define HORDE_MAX_COLS 8
#define HORDE_INITIAL_COLS 2
#define HORDE_LEVELS_PER_COL NUM_GAME_LEVELS

#define HORDE_SHOT_DELAY_MIN_MIN 0.5
#define HORDE_SHOT_DELAY_MIN_INITIAL 1.5
#define HORDE_SHOT_DELAY_MIN_LEVEL_FACTOR 0.1
#define HORDE_SHOT_DELAY_MAX_MIN 1.5
#define HORDE_SHOT_DELAY_MAX_INITIAL 5.5
#define HORDE_SHOT_DELAY_MAX_LEVEL_FACTOR 0.1

#define HORDE_MAX_VELOCITY_MAX 5
#define HORDE_MAX_VELOCITY_FACTOR 3
#define HORDE_X_VELOCITY_INITIAL 0.5
#define HORDE_X_VELOCITY_LEVEL_FACTOR 0.1
#define HORDE_X_ACCEL_LEVEL_FACTOR 0.005
#define HORDE_Y_VELOCITY_INITIAL 0.01
#define HORDE_Y_VELOCITY_LEVEL_FACTOR 0.01
#define HORDE_Y_ACCEL_LEVEL_FACTOR 0.0025




